name: Deploy multiple projects

on:
  push:
    branches: [main]

# 添加这一块：授予写入内容的权限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 构建 manyspeech
      - name: Build manyspeech
        run: |
          cd manyspeech
          npm ci
          npm run build
          mkdir -p ../docs/manyspeech
          cp -r doc_build/* ../docs/manyspeech/
      
      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
